SELECT
    C.NOM_CLIENTE,
    COUNT(C.NOM_CLIENTE) AS "Quantidade de Pedidos"
FROM
    PEDIDO  P
    JOIN CLIENTE C
    ON P.COD_CLIENTE = C.COD_CLIENTE
GROUP BY
    C.NOM_CLIENTE
HAVING
    COUNT(C.NOM_CLIENTE) > 1
ORDER BY
    COUNT(C.NOM_CLIENTE) DESC;