DROP TABLE FATOPEDIDO CASCADE CONSTRAINTS;

DROP TABLE DIMCLIENTE CASCADE CONSTRAINTS;

DROP TABLE DIMPRODUTO CASCADE CONSTRAINTS;

DROP TABLE DIMVENDEDOR CASCADE CONSTRAINTS;

DROP TABLE DIMTEMPO CASCADE CONSTRAINTS;

DROP TABLE DIMLOCALIZACAO CASCADE CONSTRAINTS;

CREATE TABLE DIMCLIENTE (
       COD_CLIENTE INT PRIMARY KEY,
       NOM_CLIENTE VARCHAR(255),
       NUM_CPF_CNPJ VARCHAR(20),
       TIPO_CLIENTE VARCHAR(50),
       STATUS_CLIENTE VARCHAR(50)
);

CREATE TABLE DIMPRODUTO (
       COD_PRODUTO INT PRIMARY KEY,
       NOM_PRODUTO VARCHAR(255),
       COD_BARRA VARCHAR(50),
       TIPO_PRODUTO VARCHAR(50),
       STATUS_PRODUTO VARCHAR(50)
);

CREATE TABLE DIMVENDEDOR (
       COD_VENDEDOR INT PRIMARY KEY,
       NOM_VENDEDOR VARCHAR(255),
       STATUS_VENDEDOR VARCHAR(50)
);

CREATE TABLE DIMTEMPO (
       COD_TEMPO INT PRIMARY KEY,
       ANO INT,
       MES INT,
       DIA INT,
       TRIMESTRE INT,
       SEMESTRE INT,
       DIA_DA_SEMANA VARCHAR(50),
       DIA_DO_ANO INT
);

CREATE TABLE DIMLOCALIZACAO (
       COD_LOCALIZACAO INT PRIMARY KEY,
       CIDADE VARCHAR(255),
       ESTADO VARCHAR(255),
       PAIS VARCHAR(255)
);

CREATE TABLE FATOPEDIDO (
       COD_PEDIDO INT PRIMARY KEY,
       COD_CLIENTE INT,
       COD_PRODUTO INT,
       COD_VENDEDOR INT,
       COD_TEMPO INT,
       COD_LOCALIZACAO INT,
       VAL_TOTAL_PEDIDO DECIMAL(10, 2),
       QTD_ITEM INT,
       VAL_DESCONTO DECIMAL(10, 2),
       VAL_FRETE DECIMAL(10, 2),
       DAT_PEDIDO DATE,
       DAT_ENTREGA DATE,
       FOREIGN KEY (COD_CLIENTE) REFERENCES DIMCLIENTE(COD_CLIENTE),
       FOREIGN KEY (COD_PRODUTO) REFERENCES DIMPRODUTO(COD_PRODUTO),
       FOREIGN KEY (COD_VENDEDOR) REFERENCES DIMVENDEDOR(COD_VENDEDOR),
       FOREIGN KEY (COD_TEMPO) REFERENCES DIMTEMPO(COD_TEMPO),
       FOREIGN KEY (COD_LOCALIZACAO) REFERENCES DIMLOCALIZACAO(COD_LOCALIZACAO)
);